name: add issues to project

on:
  workflow_call:
    secrets:
      PROJECT_AUTOMATION_APP_PEM:
        required: true
    inputs:
      repository:
        description: 'Repository'
        required: true
        type: string
      project-number:
        description: 'Project Number'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        type: string
      project-number:
        description: 'Project Number'
        required: true
        type: string
jobs:
  graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
          owner: ${{ github.repository_owner }}
      - name: Get project data
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: CI-CMG
          PROJECT_NUMBER: ${{ inputs.project-number }}
          REPOSITORY: ${{ inputs.repository }}
        run: |
          set -e
          echo "Project $PROJECT_NUMBER"
          echo "Repository $REPOSITORY"
        
          has_next_page=true
          end_cursor=''
          page=1
          set +e
          rm page*.json
          set -e
          while [ $has_next_page = true ]; do
        
            file=page$page.json
        
            gh api graphql -f query='query($organization: String! $repository: String! $number: Int! $end_cursor: String!) {
              organization(login: $organization) {
                projectV2(number: $number) { id }
                repository(name: $repository) {
                  id
                  name
                  issues(first: 100, states: [OPEN], after: $end_cursor) {
                    pageInfo { endCursor hasNextPage }
                    nodes {
                      id
                      title
                      closed
                      projectItems(includeArchived: false, first: 100) {
                        nodes {
                          project { id number }
                        }
                      }
                    }
                  }
                }
              }
            }' -f organization=$ORGANIZATION -f repository=$REPOSITORY -F number=$PROJECT_NUMBER -f end_cursor=$end_cursor > $file
          
            end_cursor=$(jq -r '.data.organization.repository.issues.pageInfo.endCursor' $file)
            has_next_page=$(jq -r '.data.organization.repository.issues.pageInfo.hasNextPage' $file)
            
            ((page++))
            
          done
          
          jq -r ".data.organization.repository.issues.nodes[] | select(contains({projectItems:{nodes:[{project:{number:$PROJECT_NUMBER}}]}}) | not)" page*.json | jq -s > issues_not_in_project.json
          
          project_id=$(jq -r '.data.organization.projectV2.id' page1.json)
          
          cat issues_not_in_project.json
          
          count=$(jq -r '. | length' issues_not_in_project.json)
          for (( i=0; i<$count; i++ ))
            do
              issue_id=$(jq -r ".[$i].id" issues_not_in_project.json)
              echo "setting issue $issue_id on project $project_id"
              gh api graphql -f query='mutation($project_id: ID! $item_id: ID! $issue_id: ID!) {
                addProjectV2ItemById(input: {projectId: $project_id, contentId: $issue_id}) {
                  item { id }
                }
              }' -f project_id=$project_id -f issue_id=$issue_id
          done
