name: add Tugboat issues to project

on:
  workflow_call:
    secrets:
      PROJECT_AUTOMATION_APP_PEM:
        required: true
  workflow_dispatch:


jobs:
  tugboat:
    uses: ./.github/workflows/add-issues-to-project.yaml
    with:
      project-number: 27
      repository: tugboat
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
  mgg-core:
    uses: ./.github/workflows/add-issues-to-project.yaml
    with:
      project-number: 27
      repository: mgg-core
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
  mgg-core-bom:
    uses: ./.github/workflows/add-issues-to-project.yaml
    with:
      project-number: 27
      repository: mgg-core-bom
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}