name: add trackline issues to project

on:
  workflow_call:
    secrets:
      PROJECT_AUTOMATION_APP_PEM:
        required: true
  workflow_dispatch:


jobs:
  trackline-ingest:
    uses: ./.github/workflows/add-issues-to-project.yaml
    with:
      project-number: 31
      repository: trackline-ingest
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
  tharp:
    uses: ./.github/workflows/add-issues-to-project.yaml
    with:
      project-number: 31
      repository: tharp
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}