name: automated schedule

on:
  schedule:
    - cron: "*/3 * * * *"
#    - cron: "* * * * *"

jobs:
  parent-issue-to-in-progress:
    uses: ./.github/workflows/parent-issue-to-in-progress.yaml
    with:
      project-numbers: ${{ github.event.inputs.project-numbers }}
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
  set-start-date:
    uses: ./.github/workflows/set-start-date.yaml
    with:
      project-numbers: ${{ github.event.inputs.project-numbers }}
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
  set-end-date:
    uses: ./.github/workflows/set-end-date.yaml
    with:
      project-numbers: ${{ github.event.inputs.project-numbers }}
    secrets:
      PROJECT_AUTOMATION_APP_PEM: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
