name: set parent issues to in progress

on:
  workflow_dispatch:
    inputs:
      project-numbers:
        description: 'Project Numbers'
        required: true
        type: string
#  schedule:
#    - cron: "* * * * *"
jobs:
  graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
      - name: Get project data
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: CI-CMG
          PROJECT_NUMBERS: ${{ github.event.inputs.project-numbers }}
        run: |
          IFS=","
          read -ra array <<< "$PROJECT_NUMBERS"
             
          for project_number in "${array[@]}"; do
            echo "Project $project_number"
            
            gh api graphql -f query='query($organization: String! $number: Int!) {
              organization(login: $organization) {
                projectV2(number: $number) {
                  id
                  fields(first: 100) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options { id name }
                      }
                    }
                  }
                  items(first: 100, after: null) {
                    pageInfo { endCursor startCursor hasNextPage hasPreviousPage }
                    nodes { 
                      ... on ProjectV2Item { id isArchived type
                        status: fieldValueByName(name: "Status") {
                          ... on ProjectV2ItemFieldSingleSelectValue { name }
                        }
                        content {
                          ... on Issue { id state title number 
                            issueType {
                              name
                            }
                            parent { id title number state
                              issueType { name }
                            }
                            repository { id name }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' -f organization=$ORGANIZATION -F number=$project_number > project.json
            
            end_cursor=$(jq -r '.data.organization.projectV2.items.pageInfo.endCursor' project.json)
            has_next_page=$(jq -r '.data.organization.projectV2.items.pageInfo.hasNextPage' project.json)
            project_id=$(jq -r '.data.organization.projectV2.id' project.json)
            status_field_id=$(jq -r '.data.organization.projectV2.fields.nodes[] | select(.name == "Status") | .id' project.json)
            in_progress_value_id=$(jq -r '.data.organization.projectV2.fields.nodes[] | select(.name == "Status") | .options[] | select(.name == "In progress") | .id' project.json)
            
            jq -r '.data.organization.projectV2.items.nodes[] | select(.content.parent != null and .isArchived == false and (.status.name == "In review" or .status.name == "In progress" or .status.name == "Blocked") )' project.json | jq -s > with_parents.json
            
            with_parents_count=$(jq -r '. | length' with_parents.json)
            for (( i=0; i<$with_parents_count; i++ ))
            do
              repository=$(jq -r ".[$i].content.repository.name" with_parents.json)
              child=$(jq -r ".[$i].content.number" with_parents.json)
              parent=$(jq -r ".[$i].content.parent.number" with_parents.json)
              parent_id=$(jq -r ".data.organization.projectV2.items.nodes[] | select(.content.repository.name == \"$repository\" and .content.number == $parent) | .id" project.json)
              parent_status=$(jq -r ".data.organization.projectV2.items.nodes[] | select(.content.repository.name == \"$repository\" and .content.number == $parent) | .status.name" project.json)
              if [[ "$parent_status" =~ ^(Backlog|Ready|Done)$ ]]; then
                echo "update issue $repository/$parent with status $parent_status"
                gh api graphql -f query='mutation($project: ID! $item: ID! $status_field: ID! $status_value: String!) {
                  set_status: updateProjectV2ItemFieldValue(input: { projectId: $project itemId: $item fieldId: $status_field value: { singleSelectOptionId: $status_value } }) {
                    projectV2Item { id }
                  }
                }' -f project=$project_id -f item=$parent_id -f status_field=$status_field_id -f status_value=$in_progress_value_id
              fi
            done
 
          done
