name: project-automation

on:
  schedule:
    - cron: "* * * * *"
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
      - name: Get project data
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: CI-CMG
          PROJECT_NUMBER: 17
        run: |
          gh api graphql -f query='query($organization: String! $number: Int!) {
            organization(login: $organization) {
              projectV2(number: $number) {
                items(first: 100, after: null){
                  pageInfo {
                    endCursor
                    startCursor
                    hasNextPage
                    hasPreviousPage
                 }
                 nodes { 
                   ... on ProjectV2Item {
                     id
                     isArchived
                     type
                     status: fieldValueByName(name: "Status"){
                       ... on ProjectV2ItemFieldSingleSelectValue {
                         name
                       }
                     }
                     content {
                       ... on Issue { 
                         id
                         state
                         issueType {
                           name
                         }
                      number
                      parent {
                        id
                        title
                        number
                        state
                        issueType {
                          name 
                        }
                      }
                      title
                      repository {
                        id
                        name
                      }
                    }
                   }
                }
              }
            }
          }
          }
          }



          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json
          cat project_data.json
