name: project-automation

on:
  workflow_dispatch:
#  schedule:
#    - cron: "* * * * *"
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_APP_PEM }}
      - name: Get project data
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: CI-CMG
          PROJECT_NUMBER: 17
        run: |
          gh api graphql -f query='query($organization: String!) {
            organization(login: $organization) {
              projectsV2 {
                nodes {
                  id
                  number
                  title
                }
              }
            }
          }' -f organization=$ORGANIZATION > project_data.json
          cat project_data.json
